modLoader = "javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL = "${mod_issue_url}"
showAsResourcePack = false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_display_name}"
updateJSONURL="${mod_update_url}"
displayURL = "${mod_display_url}"
logoFile = "${mod_logo_file}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"

[[dependencies.${mod_id}]]
modId = "htlib"
mandatory = true
versionRange = "${htlib_version_range}"
