modLoader="javafml"
loaderVersion="[40,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/HungTeen/Immortal/issues"

[[mods]]
modId="immortal"
version="${file.jarVersion}"
displayName="Immortal"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://space.bilibili.com/362855464"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="HungTeen, GrassCrap"
description='''
I am mortal, but i will be immortal !
'''
#configBackground="pvz:textures/block/amethyst_block.png"

[[dependencies.immortal]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immortal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
