modLoader="javafml"
loaderVersion="[43,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/HungTeen/Immortal/issues"

[[mods]]
modId="immortal"
version="${file.jarVersion}"
displayName="Immortal"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://space.bilibili.com/362855464"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="HungTeen, GrassCrap"
description='''
I am mortal, but i will be immortal !
'''

[modproperties.immortal]
#configBackground="pvz:textures/block/amethyst_block.png"

[[dependencies.immortal]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"

[[dependencies.immortal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"

[[dependencies.immortal]]
modId="htlib"
mandatory=true
versionRange="[0.9.0,)"

[[dependencies.immortal]]
modId="jei"
mandatory=false
versionRange="[11.4.0.285,)"

[[dependencies.immortal]]
modId="curios"
mandatory=false
versionRange="[1.19.2-5.1.1.0,)"

[[dependencies.immortal]]
modId="patchouli"
mandatory=false
versionRange="[1.19.2-77,)"

[[dependencies.immortal]]
modId="jade"
mandatory=false
versionRange="[8.3.2,)"

[[dependencies.immortal]]
modId="configured"
mandatory=false
versionRange="[2.0.1,)"
