modLoader="javafml"
loaderVersion="${neoforge_loader_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_display_name}"
displayURL="${mod_display_url}"
issueTrackerURL = "${mod_issue_url}"
logoFile="${mod_logo_file}"
authors="${mod_authors}"
description='''${mod_description}'''
enumExtensions="META-INF/enumextensions.json"

[[accessTransformers]]
file="META-INF/accesstransformer-nf.cfg"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${ mod_id }]]
modId = "htlib"
type = "required"
versionRange = "${htlib_version_range}"
ordering = "NONE"
side = "BOTH"